const config = {
  AWS_ACCESS_KEY_ID: "REPLACE WITH YOUR AWS ID",
  AWS_SECRET_ACCESS_KEY: "REPLACE WITH YOUR AWS SECRET",
  AWS_REGION: "REPLACE WITH YOUR AWS REGION",
  S3_BUCKET_NAME: "REPLACE WITH YOUR BUCKET NAME",
};
// Do not push to git!
module.exports = config;
